package:
  name: "confbusterplusplus"
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/e-dang/ConfBusterPlusPlus.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  host:
    - python
    - rdkit 2020_03_3
    - openbabel 3.0.0
    - numpy >=1.18.1

  run:
    - python
    - rdkit 2020_03_3
    - openbabel 3.0.0
    - numpy >=1.18.1

about:
  home: https://github.com/e-dang/ConfBusterPlusPlus.git
  license: MIT
