package:
  name: "confbusterplusplus"
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/e-dang/ConfBusterPlusPlus.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
#   imports:
#     - confbusterplusplus

about:
  home: https://github.com/e-dang/ConfBusterPlusPlus.git
