package:
  name: "confbuster++"
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/e-dang/ConfBusterPlusPlus.git

requirements:
  build:
    - python
    - setuptools
    - argparse
    - numpy
    - matplotlib
    - rdkit 2019.03.2

  run:
    - python
    - argparse
    - numpy
    - matplotlib
    - rdkit 2019.03.2

test:
  imports:
    - conf_gen

about:
  home: https://github.com/e-dang/ConfBusterPlusPlus.git
