package:
  name: "confbusterplusplus"
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/e-dang/ConfBusterPlusPlus.git

requirements:
  build:
    - python
    - setuptools
    - numpy 1.18.1
    - matplotlib 3.1.1
    - conda-forge::rdkit

  run:
    - python
    - numpy 1.18.1
    - matplotlib 3.1.1
    - conda-forge::rdkit

test:
  imports:
    - confbusterplusplus

about:
  home: https://github.com/e-dang/ConfBusterPlusPlus.git
