package:
  name: "confbuster++"
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/e-dang/ConfBusterPlusPlus.git

requirements:
  build:
    - python
    - setuptools
    - argparse
    - numpy 1.18.1
    - matplotlib 3.1.1
    - rdkit 2019.03.2

  run:
    - python
    - argparse
    - numpy 1.18.1
    - matplotlib 3.1.1
    - rdkit 2019.03.2

test:
  imports:
    - confbuster++

about:
  home: https://github.com/e-dang/ConfBusterPlusPlus.git
