package:
  name: "confbusterplusplus"
  version: "1.1.0"

source:
  git_rev: master
  git_url: https://github.com/e-dang/ConfBusterPlusPlus.git

# apparently conda wont let you specify requirements in specific channels so requirements must be installed manually by
# user. See README for details.
requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/e-dang/ConfBusterPlusPlus.git
